In [2]:
import pandas as pd

In [ ]:
# UNUSED FILES
unclean = {
    'prose':[],
    'nonfiction':['WikiTV2023.csv','WikiEspGDC.csv','WikiEspAI.csv'],
    'misc':[],
    'interrogative':[],
    'fiction':['wikiAH_clean.csv'],
    'declarative':[],
    'colloquial':[]
}

alrdy_clean = {
    'prose':[],
    'nonfiction':[],
    'misc':[],
    'interrogative':[],
    'fiction':['essays_clean.csv',],
    'declarative':['bible_clean.csv'],
    'colloquial':[]
}

In [6]:
# FILES IN BLEND
files = {
    'prose':['psalms_clean.csv'],
    'nonfiction':['case_law.csv','med_trans_clean.csv'],
    'misc':['code.csv','hellaSwag_clean.csv'],
    'interrogative':['sat_qstns_clean.csv'],
    'fiction':['movie_summs_clean.csv'],
    'declarative':[],
    'colloquial':['txt_msgs_clean.csv','spam_msgs_clean.csv','email_msgs_clean.csv']
}

In [4]:
# LOGIC
keys = ['a','b','c','d','e']
df = pd.DataFrame()

for x in keys:
    df_ = pd.DataFrame({'text':['0','1','2','3','4','5']})
    data = { 'type':x, 'text':df_['text'] }
    df = pd.concat([df, pd.DataFrame(data)])
#display(df)

  type text
0    a    0
1    a    1
2    a    2
3    a    3
4    a    4
5    a    5
0    b    0
1    b    1
2    b    2
3    b    3
4    b    4
5    b    5
0    c    0
1    c    1
2    c    2
3    c    3
4    c    4
5    c    5
0    d    0
1    d    1
2    d    2
3    d    3
4    d    4
5    d    5
0    e    0
1    e    1
2    e    2
3    e    3
4    e    4
5    e    5

In [7]:
# CONCATENATOR
base_url = '../data/clean'
keys = list(files.keys())
vals = list(files.values())
df = pd.DataFrame()

for x in range(len(vals)):
    set_len = len(vals[x])
    cat = keys[x]
    for y in range(set_len):
        df_ = pd.read_csv(f'{base_url}/{cat}/{vals[x][y]}')
        data = { 'type':keys[x], 'text':df_['text'] }
        df = pd.concat([df, pd.DataFrame(data)]).reset_index(drop=True)

In [8]:
df.to_csv('../data/testBlend.csv', index=False)